Vagrant.configure("2") do |config|
  config.disksize.size = "128GB"
  config.vm.box = "cloud-image/ubuntu-24.04"
  config.vm.box_version = "20250502.1.0"
  config.vm.box_architecture = "amd64"
  config.vm.define "devkit-ubuntu-24.04" do |kata|
    kata.vm.hostname = "ubuntu"
    kata.vm.network "private_network", type: "dhcp"
    kata.vm.provider "virtualbox" do |vb|
      vb.cpus = 20
      vb.memory = "16384"
      vb.customize ["modifyvm", :id, "--nested-hw-virt", "on", "--graphicscontroller", "None"]
    end
  end
    
  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http = "http://127.0.0.1:7890/"
    config.proxy.https = "http://127.0.0.1:7890/"
    config.proxy.no_proxy = "localhost,127.0.0.1,.example.com"
  end
 end
